#!/bin/bash

top=$(dirname $0)

artwork_url=$(osascript -l JavaScript "${top}/SpotifyNowPlaying.js" artwork)
artwork="/tmp/SpotifyNowPlaying-Artwork.png"
artwork_sum="/tmp/SpotifyNowPlaying-Artwork.sha1sum"
default_artwork="/tmp/SpotifyNowPlaying-DefaultArtwork.png"

if ! test -s "$default_artwork"
then
    cp -f "${top}/DefaultArtwork/DefaultArtwork.png" "$default_artwork" || { echo "${top}/DefaultArtwork/DefaultArtwork.png not found"; exit 1; }
fi

if test -n "$artwork_url"
then
    previous_sum=$(cat "$artwork_sum" 2>/dev/null)
    current_sum=$(printf "$artwork_url" | shasum -a 1 - | awk '{print $1}')

    [[ ${previous_sum} == ${current_sum} ]] && exit 0

    echo ${current_sum} > "$artwork_sum"
    curl -s -o "$artwork" "$artwork_url"
else
    inum_default=$(stat -f '%i' "$default_artwork")
    inum_current=$(stat -f '%i' "$artwork")
    if [[ ${inum_default} -ne ${inum_current} ]]
    then
        ln -f "$default_artwork" "$artwork"
        rm -f "$artwork_sum"
    fi
fi
